INSTANCE_ID=near_30_days
INSTANCE_NAME="Near 30 Days"
INSTANCE_PORT=8501
INSTANCE_DATA_DIR=/home/jf/Projects/OTA-SCRAPER-LINUX/data/instances/near_30_days
INSTANCE_CITY=Orlando
INSTANCE_SOURCE=Booking.com
INSTANCE_DATE_BUCKET=near_30_days
DB_BACKEND=sqlite
OTA_BROWSER_HEADLESS=1
OTA_DRIVE_FOLDER_ID=18kkxujFodzEfoOmhfpBuZI8xDzaoUk8b
INSTANCE_WORKSPACE_NAME="SCRAPER 1"
INSTANCE_WINDOW_CLASS=ota-scraper-instance-1
